# platform: linux-64
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch==2.1
  - torchvision=0.16
  - torchdata=0.7
  - pytorch-cuda=12.1
  - opacus=1.4
  - numpy=1.26
  - matplotlib=3.8
  - scipy=1.11
  - scikit-learn=1.3
  - python-dotenv=1.0
  - tqdm=4.66
  - ruff=0.1
  - mlflow=2.8
  - filelock=3.13
  # Only for dataset generation
  - open-clip-torch=2.23
  - jupyterlab=4.0
  - ipywidgets=8.1
